require("kurt.plugins-setup")
require("kurt.core.options")
require("kurt.core.keymaps")
require("kurt.core.colorscheme")

-- require("kurt.plugins.avante")
require("kurt.plugins.bufferline")
require("kurt.plugins.comment")
require("kurt.plugins.gitsigns")
require("kurt.plugins.lualine")
require("kurt.plugins.neoterm")
require("kurt.plugins.nvim-cmp")
require("kurt.plugins.nvim-tree")
require("kurt.plugins.telescope")
require("kurt.plugins.treesitter")
require("kurt.plugins.nvim-neotest")
require("kurt.plugins.lsp.lspconfig")
require("kurt.plugins.vim-dadbod")
