-- local copilot_setup, copilot = pcall(require, "copilot")
-- local copilot_cmp_setup, copilot_cmp = pcall(require, "copilot_cmp")
--
-- if not copilot_setup then
--   return
-- end
--
-- if not copilot_cmp_setup then
--   copilot.setup()
-- else
--   copilot.setup({
--     suggestion = { enabled = false },
--     panel = { enabled = false },
--   })
--
--   copilot_cmp.setup({
--     sources = {
--       { name = "copilot", group_index = 2 },
--     },
--   })
-- end
